# Generated by Django 3.1.7 on 2021-03-04 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=300)),
                ('uasg_orgao', models.PositiveIntegerField()),
                ('no_arp', models.CharField(max_length=300)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
