# Generated by Django 3.1.7 on 2021-02-25 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
