# Generated by Django 3.1.7 on 2021-03-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licitacao', '0001_initial'),
        ('Produto', '0003_remove_produto_data_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='licitacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Licitacao.licitacao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='no_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
