# Generated by Django 3.1.7 on 2021-03-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Licitacao', '0001_initial'),
        ('Produto', '0004_auto_20210304_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='licitacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Licitacao.licitacao'),
        ),
    ]
