# Generated by Django 3.1.7 on 2021-03-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0004_auto_20210304_1750'),
        ('Pedido', '0002_auto_20210304_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Pedido.pedido'),
        ),
        migrations.AlterField(
            model_name='elementos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Produto.produto'),
        ),
    ]
